### ISSUE TITLE
Missing File "imdb_train_global_rule.npy"

### ISSUE THREAD

**Issue by nmalboubi** [guanghuixu/AnchorCaptioner#3]
I'm trying to use the pre-trained model, but getting this error below (it seems the imdb_train_global_rule.npy file is missing). I downnloaded all the text caps data and this file wasn't a part of it:

2021-07-11T07:22:59 ERROR: [Errno 2] No such file or directory: '/home/ec2-user/AnchorCaptioner/pythia/../data/imdb/m4c_coco/imdb_karpathy_train.npy'
Traceback (most recent call last):
  File "tools/run.py", line 102, in <module>
    run()
  File "tools/run.py", line 90, in run
    trainer.load()
  File "/home/ec2-user/AnchorCaptioner/pythia/trainers/base_trainer.py", line 62, in load
    self.load_task()
  File "/home/ec2-user/AnchorCaptioner/pythia/trainers/base_trainer.py", line 93, in load_task
    self.dataset_loader.load_datasets()
  File "/home/ec2-user/AnchorCaptioner/pythia/common/dataset_loader.py", line 23, in load_datasets
    self.train_dataset.load(**self.config)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/multi_dataset.py", line 81, in load
    dataset_instance = builder_instance.load(self._dataset_type, attributes)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/base_dataset_builder.py", line 68, in load
    dataset = self._load(dataset_type, config, *args, **kwargs)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/vqa2/builder.py", line 32, in _load
    self.dataset = self.prepare_data_set(dataset_type, config)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/vqa2/builder.py", line 84, in prepare_data_set
    dataset = cls(dataset_type, imdb_idx, config)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/captioning/m4c_textcaps/dataset.py", line 9, in __init__
    dataset_type, imdb_file_index, config, *args, **kwargs
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/m4c_textvqa/dataset.py", line 14, in __init__
    dataset_type, imdb_file_index, config, *args, **kwargs
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/textvqa/dataset.py", line 8, in __init__
    super().__init__(dataset_type, imdb_file_index, config, *args, **kwargs)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/vizwiz/dataset.py", line 10, in __init__
    super().__init__(dataset_type, imdb_file_index, config, *args, **kwargs)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/vqa/vqa2/dataset.py", line 28, in __init__
    self.imdb = ImageDatabase(self.imdb_file)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/image_database.py", line 33, in __init__
    self._load_imdb(imdb_path)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/image_database.py", line 37, in _load_imdb
    self._load_npy(imdb_path)
  File "/home/ec2-user/AnchorCaptioner/pythia/datasets/image_database.py", line 54, in _load_npy
    self.db = np.load(imdb_path, allow_pickle=True)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/AnchorCaptioner/pythia/../data/imdb/m4c_coco/imdb_karpathy_train.npy'
[ec2-user@ip-172-31-45-174 AnchorCaptioner]$

**Comment by guanghuixu** [comment]
Please refer to https://github.com/guanghuixu/AnchorCaptioner/releases/tag/data

**Comment by nmalboubi** [comment]
Thank you so much! Appreciate the swift reply!
